repositories:
  # Prometheus community charts, https://github.com/prometheus-community/helm-charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  # Grafana charts, https://github.com/grafana/helm-charts/tree/main/charts/loki-stack
  - name: grafana
    url: https://grafana.github.io/helm-charts

## Namespace to which the helm charts will be installed.
namespace: observability

releases:
  # Prometheus, Grafana ## More details here https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/README.md
  - name: kube-prometheus-stack
    chart: prometheus-community/kube-prometheus-stack
    values:
      - values/kube-prometheus-stack.yaml.gotmpl

  # Loki, Promtail ## 
  - name: loki-stack
    chart: grafana/loki-stack
    values:
      - values/loki-stack.yaml.gotmpl
  # Tempo
  - name: tempo
    chart: grafana/tempo
    values:
      - values/tempo.yaml.gotmpl

# values:
#   - .env.{{ .Environment.Name }}.yaml
